name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-format-and-static-code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.11

      - name: Install pre-commit
        run: |
          uv pip install pre-commit

      - name: Run Lint, Format, and other static code quality checks
        run: |
          make lint-ci
